//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Generated
{
    using System;
    using Umbraco.InteractionLayer.Library;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// Contact page
    /// </summary>
    [UmbracoDocTypeInfo(Alias="Contact Page", Id=1067)]
    public partial class ContactPage : DocTypeBase
    {
        
        private string _PageHeader;
        
        private string _bodyText;
        
        private string _secondaryText;
        
        private string _EmailTo;
        
        private string _EmailSubject;
        
        private string _EmailMessage;
        
        private string _EmailReplyFrom;
        
        private string _EmailReplySubject;
        
        private string _EmailReplyMessage;
        
        private string _MailServer;
        
        private string _ServerUser;
        
        private string _ServerPass;
        
        private int _Redirect;
        
        private string _PageTitle;
        
        private string _Description;
        
        private string _Keywords;
        
        private int _umbracoNaviHide;
        
        private System.Collections.Generic.IEnumerable<TextPage> _TextPages;
        
        public ContactPage()
        {
            this.IsDirty = true;
        }
        
        public ContactPage(int id) : 
                this(new umbraco.cms.businesslogic.web.Document(id))
        {
        }
        
        public ContactPage(System.Guid uniqueId) : 
                this(new umbraco.cms.businesslogic.web.Document(uniqueId))
        {
        }
        
        protected internal ContactPage(umbraco.cms.businesslogic.web.Document source) : 
                base(source)
        {
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Header", Mandatory=true, IsCustom=true, Alias="PageHeader")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageHeader")]
        public virtual string PageHeader
        {
            get
            {
                return this._PageHeader;
            }
            set
            {
                if ((this.PageHeader != value))
                {
                    this.RaisePropertyChanging();
                    this._PageHeader = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageHeader");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Content", Mandatory=false, IsCustom=true, Alias="bodyText")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="bodyText")]
        public virtual string bodyText
        {
            get
            {
                return this._bodyText;
            }
            set
            {
                if ((this.bodyText != value))
                {
                    this.RaisePropertyChanging();
                    this._bodyText = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("bodyText");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Secondary Content", Mandatory=false, IsCustom=true, Alias="secondaryText")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="secondaryText")]
        public virtual string secondaryText
        {
            get
            {
                return this._secondaryText;
            }
            set
            {
                if ((this.secondaryText != value))
                {
                    this.RaisePropertyChanging();
                    this._secondaryText = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("secondaryText");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email To", Mandatory=true, IsCustom=true, Alias="EmailTo")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailTo")]
        public virtual string EmailTo
        {
            get
            {
                return this._EmailTo;
            }
            set
            {
                ValidateProperty("^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\." +
                        ")+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$", value);
                if ((this.EmailTo != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailTo = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Subject", Mandatory=true, IsCustom=true, Alias="EmailSubject")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailSubject")]
        public virtual string EmailSubject
        {
            get
            {
                return this._EmailSubject;
            }
            set
            {
                if ((this.EmailSubject != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailSubject = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailSubject");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Message (Use [Name], [Email], [Message], [Time] and [Date]", Mandatory=true, IsCustom=true, Alias="EmailMessage")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailMessage")]
        public virtual string EmailMessage
        {
            get
            {
                return this._EmailMessage;
            }
            set
            {
                if ((this.EmailMessage != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailMessage = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailMessage");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Reply (The email address the thankyou message uses to the customer)", Mandatory=true, IsCustom=true, Alias="EmailReplyFrom")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailReplyFrom")]
        public virtual string EmailReplyFrom
        {
            get
            {
                return this._EmailReplyFrom;
            }
            set
            {
                if ((this.EmailReplyFrom != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailReplyFrom = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailReplyFrom");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Reply Subject (The Email subject the thankyou message uses to the customer)" +
            "", Mandatory=true, IsCustom=true, Alias="EmailReplySubject")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailReplySubject")]
        public virtual string EmailReplySubject
        {
            get
            {
                return this._EmailReplySubject;
            }
            set
            {
                if ((this.EmailReplySubject != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailReplySubject = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailReplySubject");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Reply Message (Use [Name])", Mandatory=true, IsCustom=true, Alias="EmailReplyMessage")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailReplyMessage")]
        public virtual string EmailReplyMessage
        {
            get
            {
                return this._EmailReplyMessage;
            }
            set
            {
                if ((this.EmailReplyMessage != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailReplyMessage = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailReplyMessage");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Server (mail.yourserver.co.uk)", Mandatory=true, IsCustom=true, Alias="MailServer")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="MailServer")]
        public virtual string MailServer
        {
            get
            {
                return this._MailServer;
            }
            set
            {
                if ((this.MailServer != value))
                {
                    this.RaisePropertyChanging();
                    this._MailServer = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("MailServer");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Mail Server Username", Mandatory=true, IsCustom=true, Alias="ServerUser")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="ServerUser")]
        public virtual string ServerUser
        {
            get
            {
                return this._ServerUser;
            }
            set
            {
                if ((this.ServerUser != value))
                {
                    this.RaisePropertyChanging();
                    this._ServerUser = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("ServerUser");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Mail Server Password", Mandatory=true, IsCustom=true, Alias="ServerPass")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="ServerPass")]
        public virtual string ServerPass
        {
            get
            {
                return this._ServerPass;
            }
            set
            {
                if ((this.ServerPass != value))
                {
                    this.RaisePropertyChanging();
                    this._ServerPass = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("ServerPass");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Redirect", Mandatory=false, IsCustom=true, Alias="Redirect")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Redirect")]
        public virtual int Redirect
        {
            get
            {
                return this._Redirect;
            }
            set
            {
                if ((this.Redirect != value))
                {
                    this.RaisePropertyChanging();
                    this._Redirect = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Redirect");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Title", Mandatory=true, IsCustom=true, Alias="PageTitle")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageTitle")]
        public virtual string PageTitle
        {
            get
            {
                return this._PageTitle;
            }
            set
            {
                if ((this.PageTitle != value))
                {
                    this.RaisePropertyChanging();
                    this._PageTitle = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Description (Upto 255 characters)", Mandatory=false, IsCustom=true, Alias="Description")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this.Description != value))
                {
                    this.RaisePropertyChanging();
                    this._Description = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Keywords (Seperate keywords with commas)", Mandatory=false, IsCustom=true, Alias="Keywords")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Keywords")]
        public virtual string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                if ((this.Keywords != value))
                {
                    this.RaisePropertyChanging();
                    this._Keywords = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Hidden page (Hidden from Navi and Sitemap)", Mandatory=false, IsCustom=true, Alias="umbracoNaviHide")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="umbracoNaviHide")]
        public virtual int umbracoNaviHide
        {
            get
            {
                return this._umbracoNaviHide;
            }
            set
            {
                if ((this.umbracoNaviHide != value))
                {
                    this.RaisePropertyChanging();
                    this._umbracoNaviHide = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("umbracoNaviHide");
                }
            }
        }
        
        public System.Collections.Generic.IEnumerable<TextPage> TextPages
        {
            get
            {
                if ((this._TextPages == null))
                {
                    this._TextPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1057).Select(d => new TextPage(d));;
                }
                return this._TextPages;
            }
        }
    }
}
