//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Generated
{
    using System;
    using Umbraco.InteractionLayer.Library;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    [UmbracoDocTypeInfo(Alias="Email A Friend Page", Id=1066)]
    public partial class EmailAFriendPage : DocTypeBase
    {
        
        private string _PageHeader;
        
        private string _bodyText;
        
        private string _secondaryText;
        
        private string _EmailSubjectToFriend;
        
        private string _EmailMessageToFriend;
        
        private string _EmailFrom;
        
        private string _MailServer;
        
        private string _ServerUser;
        
        private string _ServerPass;
        
        private int _Redirect;
        
        private string _PageTitle;
        
        private string _Description;
        
        private string _Keywords;
        
        private int _umbracoNaviHide;
        
        private System.Collections.Generic.IEnumerable<TextPage> _TextPages;
        
        public EmailAFriendPage()
        {
            this.IsDirty = true;
        }
        
        public EmailAFriendPage(int id) : 
                this(new umbraco.cms.businesslogic.web.Document(id))
        {
        }
        
        public EmailAFriendPage(System.Guid uniqueId) : 
                this(new umbraco.cms.businesslogic.web.Document(uniqueId))
        {
        }
        
        protected internal EmailAFriendPage(umbraco.cms.businesslogic.web.Document source) : 
                base(source)
        {
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Header", Mandatory=true, IsCustom=true, Alias="PageHeader")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageHeader")]
        public virtual string PageHeader
        {
            get
            {
                return this._PageHeader;
            }
            set
            {
                if ((this.PageHeader != value))
                {
                    this.RaisePropertyChanging();
                    this._PageHeader = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageHeader");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Content", Mandatory=false, IsCustom=true, Alias="bodyText")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="bodyText")]
        public virtual string bodyText
        {
            get
            {
                return this._bodyText;
            }
            set
            {
                if ((this.bodyText != value))
                {
                    this.RaisePropertyChanging();
                    this._bodyText = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("bodyText");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Secondary Content", Mandatory=false, IsCustom=true, Alias="secondaryText")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="secondaryText")]
        public virtual string secondaryText
        {
            get
            {
                return this._secondaryText;
            }
            set
            {
                if ((this.secondaryText != value))
                {
                    this.RaisePropertyChanging();
                    this._secondaryText = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("secondaryText");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Subject to Friend", Mandatory=true, IsCustom=true, Alias="EmailSubjectToFriend")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailSubjectToFriend")]
        public virtual string EmailSubjectToFriend
        {
            get
            {
                return this._EmailSubjectToFriend;
            }
            set
            {
                if ((this.EmailSubjectToFriend != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailSubjectToFriend = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailSubjectToFriend");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Message to Friend", Mandatory=true, IsCustom=true, Alias="EmailMessageToFriend")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailMessageToFriend")]
        public virtual string EmailMessageToFriend
        {
            get
            {
                return this._EmailMessageToFriend;
            }
            set
            {
                if ((this.EmailMessageToFriend != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailMessageToFriend = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailMessageToFriend");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email sent from", Mandatory=true, IsCustom=true, Alias="EmailFrom")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="EmailFrom")]
        public virtual string EmailFrom
        {
            get
            {
                return this._EmailFrom;
            }
            set
            {
                if ((this.EmailFrom != value))
                {
                    this.RaisePropertyChanging();
                    this._EmailFrom = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("EmailFrom");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Email Server (mail.yourserver.co.uk)", Mandatory=true, IsCustom=true, Alias="MailServer")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="MailServer")]
        public virtual string MailServer
        {
            get
            {
                return this._MailServer;
            }
            set
            {
                if ((this.MailServer != value))
                {
                    this.RaisePropertyChanging();
                    this._MailServer = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("MailServer");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Mail Server Username", Mandatory=true, IsCustom=true, Alias="ServerUser")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="ServerUser")]
        public virtual string ServerUser
        {
            get
            {
                return this._ServerUser;
            }
            set
            {
                if ((this.ServerUser != value))
                {
                    this.RaisePropertyChanging();
                    this._ServerUser = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("ServerUser");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Mail Server Password", Mandatory=true, IsCustom=true, Alias="ServerPass")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="ServerPass")]
        public virtual string ServerPass
        {
            get
            {
                return this._ServerPass;
            }
            set
            {
                if ((this.ServerPass != value))
                {
                    this.RaisePropertyChanging();
                    this._ServerPass = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("ServerPass");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Redirect", Mandatory=false, IsCustom=true, Alias="Redirect")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Redirect")]
        public virtual int Redirect
        {
            get
            {
                return this._Redirect;
            }
            set
            {
                if ((this.Redirect != value))
                {
                    this.RaisePropertyChanging();
                    this._Redirect = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Redirect");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Title", Mandatory=true, IsCustom=true, Alias="PageTitle")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageTitle")]
        public virtual string PageTitle
        {
            get
            {
                return this._PageTitle;
            }
            set
            {
                if ((this.PageTitle != value))
                {
                    this.RaisePropertyChanging();
                    this._PageTitle = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Description (Upto 255 characters)", Mandatory=false, IsCustom=true, Alias="Description")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this.Description != value))
                {
                    this.RaisePropertyChanging();
                    this._Description = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Keywords (Seperate keywords with commas)", Mandatory=false, IsCustom=true, Alias="Keywords")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Keywords")]
        public virtual string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                if ((this.Keywords != value))
                {
                    this.RaisePropertyChanging();
                    this._Keywords = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Hidden page (Hidden from Navi and Sitemap)", Mandatory=false, IsCustom=true, Alias="umbracoNaviHide")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="umbracoNaviHide")]
        public virtual int umbracoNaviHide
        {
            get
            {
                return this._umbracoNaviHide;
            }
            set
            {
                if ((this.umbracoNaviHide != value))
                {
                    this.RaisePropertyChanging();
                    this._umbracoNaviHide = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("umbracoNaviHide");
                }
            }
        }
        
        public System.Collections.Generic.IEnumerable<TextPage> TextPages
        {
            get
            {
                if ((this._TextPages == null))
                {
                    this._TextPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1057).Select(d => new TextPage(d));;
                }
                return this._TextPages;
            }
        }
    }
}
