//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Generated
{
    using System;
    using Umbraco.InteractionLayer.Library;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    [UmbracoDocTypeInfo(Alias="Folder", Id=1091)]
    public partial class Folder : DocTypeBase
    {
        
        private System.Collections.Generic.IEnumerable<HomePage> _HomePages;
        
        private System.Collections.Generic.IEnumerable<TextPage> _TextPages;
        
        private System.Collections.Generic.IEnumerable<SearchPage> _SearchPages;
        
        private System.Collections.Generic.IEnumerable<GoogleSitemap> _GoogleSitemaps;
        
        private System.Collections.Generic.IEnumerable<NewsEventsListPage> _NewsEventsListPages;
        
        private System.Collections.Generic.IEnumerable<Event> _Events;
        
        private System.Collections.Generic.IEnumerable<News> _Newss;
        
        private System.Collections.Generic.IEnumerable<GalleriesListPage> _GalleriesListPages;
        
        private System.Collections.Generic.IEnumerable<Gallery> _Galleries;
        
        private System.Collections.Generic.IEnumerable<Photo> _Photos;
        
        private System.Collections.Generic.IEnumerable<EmailAFriendPage> _EmailAFriendPages;
        
        private System.Collections.Generic.IEnumerable<ContactPage> _ContactPages;
        
        private System.Collections.Generic.IEnumerable<Folder> _Folders;
        
        public Folder()
        {
            this.IsDirty = true;
        }
        
        public Folder(int id) : 
                this(new umbraco.cms.businesslogic.web.Document(id))
        {
        }
        
        public Folder(System.Guid uniqueId) : 
                this(new umbraco.cms.businesslogic.web.Document(uniqueId))
        {
        }
        
        protected internal Folder(umbraco.cms.businesslogic.web.Document source) : 
                base(source)
        {
        }
        
        public System.Collections.Generic.IEnumerable<HomePage> HomePages
        {
            get
            {
                if ((this._HomePages == null))
                {
                    this._HomePages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1056).Select(d => new HomePage(d));;
                }
                return this._HomePages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<TextPage> TextPages
        {
            get
            {
                if ((this._TextPages == null))
                {
                    this._TextPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1057).Select(d => new TextPage(d));;
                }
                return this._TextPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<SearchPage> SearchPages
        {
            get
            {
                if ((this._SearchPages == null))
                {
                    this._SearchPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1058).Select(d => new SearchPage(d));;
                }
                return this._SearchPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<GoogleSitemap> GoogleSitemaps
        {
            get
            {
                if ((this._GoogleSitemaps == null))
                {
                    this._GoogleSitemaps = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1059).Select(d => new GoogleSitemap(d));;
                }
                return this._GoogleSitemaps;
            }
        }
        
        public System.Collections.Generic.IEnumerable<NewsEventsListPage> NewsEventsListPages
        {
            get
            {
                if ((this._NewsEventsListPages == null))
                {
                    this._NewsEventsListPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1060).Select(d => new NewsEventsListPage(d));;
                }
                return this._NewsEventsListPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<Event> Events
        {
            get
            {
                if ((this._Events == null))
                {
                    this._Events = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1061).Select(d => new Event(d));;
                }
                return this._Events;
            }
        }
        
        public System.Collections.Generic.IEnumerable<News> Newss
        {
            get
            {
                if ((this._Newss == null))
                {
                    this._Newss = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1062).Select(d => new News(d));;
                }
                return this._Newss;
            }
        }
        
        public System.Collections.Generic.IEnumerable<GalleriesListPage> GalleriesListPages
        {
            get
            {
                if ((this._GalleriesListPages == null))
                {
                    this._GalleriesListPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1063).Select(d => new GalleriesListPage(d));;
                }
                return this._GalleriesListPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<Gallery> Galleries
        {
            get
            {
                if ((this._Galleries == null))
                {
                    this._Galleries = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1064).Select(d => new Gallery(d));;
                }
                return this._Galleries;
            }
        }
        
        public System.Collections.Generic.IEnumerable<Photo> Photos
        {
            get
            {
                if ((this._Photos == null))
                {
                    this._Photos = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1065).Select(d => new Photo(d));;
                }
                return this._Photos;
            }
        }
        
        public System.Collections.Generic.IEnumerable<EmailAFriendPage> EmailAFriendPages
        {
            get
            {
                if ((this._EmailAFriendPages == null))
                {
                    this._EmailAFriendPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1066).Select(d => new EmailAFriendPage(d));;
                }
                return this._EmailAFriendPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<ContactPage> ContactPages
        {
            get
            {
                if ((this._ContactPages == null))
                {
                    this._ContactPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1067).Select(d => new ContactPage(d));;
                }
                return this._ContactPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<Folder> Folders
        {
            get
            {
                if ((this._Folders == null))
                {
                    this._Folders = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1091).Select(d => new Folder(d));;
                }
                return this._Folders;
            }
        }
    }
}
