//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Generated
{
    using System;
    using Umbraco.InteractionLayer.Library;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    [UmbracoDocTypeInfo(Alias="Google Sitemap", Id=1059)]
    public partial class GoogleSitemap : DocTypeBase
    {
        
        private string _DomainURL;
        
        private int _umbracoNaviHide;
        
        public GoogleSitemap()
        {
            this.IsDirty = true;
        }
        
        public GoogleSitemap(int id) : 
                this(new umbraco.cms.businesslogic.web.Document(id))
        {
        }
        
        public GoogleSitemap(System.Guid uniqueId) : 
                this(new umbraco.cms.businesslogic.web.Document(uniqueId))
        {
        }
        
        protected internal GoogleSitemap(umbraco.cms.businesslogic.web.Document source) : 
                base(source)
        {
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="URL (http://www.mywebsite.co.uk)", Mandatory=true, IsCustom=true, Alias="DomainURL")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="DomainURL")]
        public virtual string DomainURL
        {
            get
            {
                return this._DomainURL;
            }
            set
            {
                if ((this.DomainURL != value))
                {
                    this.RaisePropertyChanging();
                    this._DomainURL = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("DomainURL");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Hidden page (Hidden from Navi and Sitemap)", Mandatory=false, IsCustom=true, Alias="umbracoNaviHide")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="umbracoNaviHide")]
        public virtual int umbracoNaviHide
        {
            get
            {
                return this._umbracoNaviHide;
            }
            set
            {
                if ((this.umbracoNaviHide != value))
                {
                    this.RaisePropertyChanging();
                    this._umbracoNaviHide = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("umbracoNaviHide");
                }
            }
        }
    }
}
