//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Generated
{
    using System;
    using Umbraco.InteractionLayer.Library;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    [UmbracoDocTypeInfo(Alias="Home Page", Id=1056)]
    public partial class HomePage : DocTypeBase
    {
        
        private string _PageHeader;
        
        private string _bodyText;
        
        private int _NoNewsEvents;
        
        private string _PageTitle;
        
        private string _Description;
        
        private string _Keywords;
        
        private int _umbracoNaviHide;
        
        private System.Collections.Generic.IEnumerable<TextPage> _TextPages;
        
        private System.Collections.Generic.IEnumerable<SearchPage> _SearchPages;
        
        private System.Collections.Generic.IEnumerable<GoogleSitemap> _GoogleSitemaps;
        
        private System.Collections.Generic.IEnumerable<NewsEventsListPage> _NewsEventsListPages;
        
        private System.Collections.Generic.IEnumerable<GalleriesListPage> _GalleriesListPages;
        
        private System.Collections.Generic.IEnumerable<EmailAFriendPage> _EmailAFriendPages;
        
        private System.Collections.Generic.IEnumerable<ContactPage> _ContactPages;
        
        public HomePage()
        {
            this.IsDirty = true;
        }
        
        public HomePage(int id) : 
                this(new umbraco.cms.businesslogic.web.Document(id))
        {
        }
        
        public HomePage(System.Guid uniqueId) : 
                this(new umbraco.cms.businesslogic.web.Document(uniqueId))
        {
        }
        
        protected internal HomePage(umbraco.cms.businesslogic.web.Document source) : 
                base(source)
        {
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Header", Mandatory=true, IsCustom=true, Alias="PageHeader")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageHeader")]
        public virtual string PageHeader
        {
            get
            {
                return this._PageHeader;
            }
            set
            {
                if ((this.PageHeader != value))
                {
                    this.RaisePropertyChanging();
                    this._PageHeader = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageHeader");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Content", Mandatory=false, IsCustom=true, Alias="bodyText")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="bodyText")]
        public virtual string bodyText
        {
            get
            {
                return this._bodyText;
            }
            set
            {
                if ((this.bodyText != value))
                {
                    this.RaisePropertyChanging();
                    this._bodyText = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("bodyText");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Number of News/Events listed", Mandatory=true, IsCustom=true, Alias="NoNewsEvents")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="NoNewsEvents")]
        public virtual int NoNewsEvents
        {
            get
            {
                return this._NoNewsEvents;
            }
            set
            {
                if ((this.NoNewsEvents != value))
                {
                    this.RaisePropertyChanging();
                    this._NoNewsEvents = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("NoNewsEvents");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Title", Mandatory=true, IsCustom=true, Alias="PageTitle")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageTitle")]
        public virtual string PageTitle
        {
            get
            {
                return this._PageTitle;
            }
            set
            {
                if ((this.PageTitle != value))
                {
                    this.RaisePropertyChanging();
                    this._PageTitle = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Description (Upto 255 characters)", Mandatory=false, IsCustom=true, Alias="Description")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this.Description != value))
                {
                    this.RaisePropertyChanging();
                    this._Description = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Keywords (Seperate keywords with commas)", Mandatory=false, IsCustom=true, Alias="Keywords")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Keywords")]
        public virtual string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                if ((this.Keywords != value))
                {
                    this.RaisePropertyChanging();
                    this._Keywords = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Hidden page (Hidden from Navi and Sitemap)", Mandatory=false, IsCustom=true, Alias="umbracoNaviHide")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="umbracoNaviHide")]
        public virtual int umbracoNaviHide
        {
            get
            {
                return this._umbracoNaviHide;
            }
            set
            {
                if ((this.umbracoNaviHide != value))
                {
                    this.RaisePropertyChanging();
                    this._umbracoNaviHide = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("umbracoNaviHide");
                }
            }
        }
        
        public System.Collections.Generic.IEnumerable<TextPage> TextPages
        {
            get
            {
                if ((this._TextPages == null))
                {
                    this._TextPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1057).Select(d => new TextPage(d));;
                }
                return this._TextPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<SearchPage> SearchPages
        {
            get
            {
                if ((this._SearchPages == null))
                {
                    this._SearchPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1058).Select(d => new SearchPage(d));;
                }
                return this._SearchPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<GoogleSitemap> GoogleSitemaps
        {
            get
            {
                if ((this._GoogleSitemaps == null))
                {
                    this._GoogleSitemaps = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1059).Select(d => new GoogleSitemap(d));;
                }
                return this._GoogleSitemaps;
            }
        }
        
        public System.Collections.Generic.IEnumerable<NewsEventsListPage> NewsEventsListPages
        {
            get
            {
                if ((this._NewsEventsListPages == null))
                {
                    this._NewsEventsListPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1060).Select(d => new NewsEventsListPage(d));;
                }
                return this._NewsEventsListPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<GalleriesListPage> GalleriesListPages
        {
            get
            {
                if ((this._GalleriesListPages == null))
                {
                    this._GalleriesListPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1063).Select(d => new GalleriesListPage(d));;
                }
                return this._GalleriesListPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<EmailAFriendPage> EmailAFriendPages
        {
            get
            {
                if ((this._EmailAFriendPages == null))
                {
                    this._EmailAFriendPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1066).Select(d => new EmailAFriendPage(d));;
                }
                return this._EmailAFriendPages;
            }
        }
        
        public System.Collections.Generic.IEnumerable<ContactPage> ContactPages
        {
            get
            {
                if ((this._ContactPages == null))
                {
                    this._ContactPages = this._umbracoDocument.Children.Where(d => d.ContentType.Id == 1067).Select(d => new ContactPage(d));;
                }
                return this._ContactPages;
            }
        }
    }
}
