//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Generated
{
    using System;
    using Umbraco.InteractionLayer.Library;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    [UmbracoDocTypeInfo(Alias="Search Page", Id=1058)]
    public partial class SearchPage : DocTypeBase
    {
        
        private string _ShortName;
        
        private string _OpenDescription;
        
        private string _Tags;
        
        private string _SiteURL;
        
        private string _PageTitle;
        
        private string _Description;
        
        private string _Keywords;
        
        private int _umbracoNaviHide;
        
        public SearchPage()
        {
            this.IsDirty = true;
        }
        
        public SearchPage(int id) : 
                this(new umbraco.cms.businesslogic.web.Document(id))
        {
        }
        
        public SearchPage(System.Guid uniqueId) : 
                this(new umbraco.cms.businesslogic.web.Document(uniqueId))
        {
        }
        
        protected internal SearchPage(umbraco.cms.businesslogic.web.Document source) : 
                base(source)
        {
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Open Search - Short Name", Mandatory=true, IsCustom=true, Alias="ShortName")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="ShortName")]
        public virtual string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                if ((this.ShortName != value))
                {
                    this.RaisePropertyChanging();
                    this._ShortName = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Open Search - Description", Mandatory=true, IsCustom=true, Alias="OpenDescription")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="OpenDescription")]
        public virtual string OpenDescription
        {
            get
            {
                return this._OpenDescription;
            }
            set
            {
                if ((this.OpenDescription != value))
                {
                    this.RaisePropertyChanging();
                    this._OpenDescription = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("OpenDescription");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Open Search - Tags", Mandatory=false, IsCustom=true, Alias="Tags")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Tags")]
        public virtual string Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                if ((this.Tags != value))
                {
                    this.RaisePropertyChanging();
                    this._Tags = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="URL (http://www.mywebsite.co.uk/)", Mandatory=true, IsCustom=true, Alias="SiteURL")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="SiteURL")]
        public virtual string SiteURL
        {
            get
            {
                return this._SiteURL;
            }
            set
            {
                if ((this.SiteURL != value))
                {
                    this.RaisePropertyChanging();
                    this._SiteURL = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("SiteURL");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Page Title", Mandatory=true, IsCustom=true, Alias="PageTitle")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="PageTitle")]
        public virtual string PageTitle
        {
            get
            {
                return this._PageTitle;
            }
            set
            {
                if ((this.PageTitle != value))
                {
                    this.RaisePropertyChanging();
                    this._PageTitle = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Description (Upto 255 characters)", Mandatory=false, IsCustom=true, Alias="Description")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this.Description != value))
                {
                    this.RaisePropertyChanging();
                    this._Description = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Keywords (Seperate keywords with commas)", Mandatory=false, IsCustom=true, Alias="Keywords")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="Keywords")]
        public virtual string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                if ((this.Keywords != value))
                {
                    this.RaisePropertyChanging();
                    this._Keywords = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        [UmbracoFieldInfo(DisplayName="Hidden page (Hidden from Navi and Sitemap)", Mandatory=false, IsCustom=true, Alias="umbracoNaviHide")]
        [System.Runtime.Serialization.DataMemberAttribute(Name="umbracoNaviHide")]
        public virtual int umbracoNaviHide
        {
            get
            {
                return this._umbracoNaviHide;
            }
            set
            {
                if ((this.umbracoNaviHide != value))
                {
                    this.RaisePropertyChanging();
                    this._umbracoNaviHide = value;
                    this.IsDirty = true;
                    this.RaisePropertyChanged("umbracoNaviHide");
                }
            }
        }
    }
}
